### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by dmr** [tobbad/pydwf#1]
Hi,
are you still using this project?
Thanks for building this wrapper, the C-API is a pain :)

**Comment by tobbad** [comment]
Thanks. It was a quick hack for my former employer where I had a Analog Discovery to test the software. As at the moment I have no employer and no Analog Discovery. Therefore this project is in deep sleep mode.

**Comment by dmr** [comment]
Did you like the device, did you end up using it?

**Comment by tobbad** [comment]
Yeah it was OK. But I left the job and the device belonged to my employer.

Today I maybe would rather buy something from:
https://www.lab-nation.com/

**Comment by dmr** [comment]
Thanks for the reply. I like the lab nation thing, but I need 14bit+ :(
